# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  NodeCount = 2

  (1..NodeCount).each do |i|
    config.vm.define "node-centos-#{i}" do |node|
      node.vm.box = "bento/centos-7.8"
      node.vm.hostname = "node-centos-#{i}"
      node.vm.network "private_network", ip: "192.168.56.1#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "node-centos-#{i}"
        v.memory = 2048
        v.cpus = 1
      end
    end
  end

  config.vm.define "ansible-control" do |vm1|
    vm1.vm.hostname = "ansible-control"
    vm1.vm.box = "bento/centos-7.8"
    vm1.vm.network "private_network", ip: "192.168.56.30"
    
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "ansible-control"
      vb.gui = false
      vb.memory = "1024"
    end

    config.vm.provision "shell", path: "bootstrap-master.sh"
    #config.vm.provision "file", source: "id_rsa", destination: "/root/.ssh/id_rsa"
  end


end