# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu-vm-01" do |vm1|
    vm1.vm.hostname = "ubuntu-vm"
    vm1.vm.box = "bento/ubuntu-22.04"
    vm1.vm.network "private_network", ip: "192.168.56.2"
    
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-vm-01"
      vb.gui = false
      vb.memory = "1024"
    end

    vm1.vm.provision "shell", run: "always", inline: <<-SHELL
        echo "Hello from the Ubuntu VM"
    SHELL
  end

  config.vm.define "ubuntu-vm-02" do |vm1|
    vm1.vm.hostname = "ubuntu-vm-02"
    vm1.vm.box = "bento/ubuntu-22.04"
    vm1.vm.network "private_network", ip: "192.168.56.3"
    
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-vm-02"
      vb.gui = false
      vb.memory = "1024"
    end

    vm1.vm.provision "shell", run: "always", inline: <<-SHELL
        echo "Hello from the Ubuntu VM"
    SHELL
  end
  
end
