# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  
  #config.vm.provision "shell", path: "bootstrap.sh"
  
  NodeCount = 1
  (1..NodeCount).each do |i|
    config.vm.define "node-tower-#{i}" do |node|
      node.vm.box = "ansible/tower"
      node.vm.hostname = "node-centos-#{i}"
      #node.vm.network "private_network", ip: "192.168.56.#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "node-tower-#{i}"
        v.memory = 2048
        v.cpus = 2
      end
    end
  end
end
