# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  NodeCount = 2

  (1..NodeCount).each do |i|
    config.vm.define "node0#{i}" do |node|
      node.vm.box = "bento/ubuntu-22.04"
      node.vm.hostname = "node0#{i}"
      node.vm.network "private_network", ip: "192.168.56.1#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "node0#{i}"
        v.memory = 2048
        v.cpus = 1
      end
      vm1.vm.provision "shell", run: "always", inline: <<-SHELL
          echo "Hello from the Ubuntu VM"
      SHELL
    end
  end

end